const data = {
    products: [
        {
            id: '1',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/1.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '2',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/2.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '3',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/3.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '4',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/4.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '5',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/5.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '6',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/6.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '7',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/1.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '8',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/2.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '9',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/3.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '10',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/4.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '11',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/5.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '12',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/6.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '13',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/1.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '14',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/2.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '15',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/3.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '16',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/4.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '17',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/5.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '18',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/6.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '19',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/1.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '20',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/2.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '21',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/3.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '22',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/4.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '23',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/5.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
        {
            id: '24',
            name: 'Shield',
            category: 'Drop Earring',
            tag: 'earring',
            gallery: '',
            image: '/Product_Images/Aroll/6.jpg',
            inventory: '2',
            color: 'Golden',
            price: '149',
            description: 'Description',
            numReview: '8',
            rating: '5',
            slug: 'shield',
            stars: '⭐⭐⭐⭐⭐',
        },
    ],
};
export default data;